//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMusicAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Tracks = new HashSet<Track>();
        }
    
        public int Id { get; set; }
        public Nullable<int> GSId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
