//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMusicAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadioGenre
    {
        public RadioGenre()
        {
            this.RadioStreams = new HashSet<RadioStream>();
        }
    
        public int Id { get; set; }
        public string RadioGenreName { get; set; }
        public string RadioImage { get; set; }
        public string RadioGenreKey { get; set; }
    
        public virtual ICollection<RadioStream> RadioStreams { get; set; }
    }
}
