//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMusicAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class RadioStream
    {
        public int Id { get; set; }
        public string RadioName { get; set; }
        public string RadioUrl { get; set; }
        public string Image { get; set; }
        public string StatnType { get; set; }
        public string RadioGenreName { get; set; }
        public Nullable<int> RadioGenreId { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<bool> TestedOk { get; set; }

        [IgnoreDataMember]
        public virtual RadioGenre RadioGenre { get; set; }
    }
}
