//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMusicAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    public partial class Track
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> ArtistId { get; set; }
        public string GSSongKey { get; set; }
        public string GSSongKeyUrl { get; set; }
        public string GSServerId { get; set; }
        public string GSSongId { get; set; }

        public string ArtistName { get; set; }

        public int key { get; set; }
        public string analysis_url { get; set; }
        public double energy { get; set; }
        public double liveness { get; set; }
        public double tempo { get; set; }
        public double speechiness { get; set; }
        public double acousticness { get; set; }
        public double instrumentalness { get; set; }
        public int mode { get; set; }
        public int time_signature { get; set; }
        public double duration { get; set; }
        public double loudness { get; set; }
        public string audio_md5 { get; set; }
        public double valence { get; set; }
        public double danceability { get; set; }

        [IgnoreDataMember]
        public virtual Artist Artist { get; set; }
    }
}
