//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMusicAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.UserTracks = new HashSet<UserTrack>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> ArtistId { get; set; }
        public string GSSongKey { get; set; }
        public string ArtistName { get; set; }
        public string GSSongKeyUrl { get; set; }
        public string GSServerId { get; set; }
        public string GSSongId { get; set; }
        public Nullable<int> key { get; set; }
        public string analysis_url { get; set; }
        public Nullable<double> energy { get; set; }
        public Nullable<double> liveness { get; set; }
        public Nullable<double> tempo { get; set; }
        public Nullable<double> speechiness { get; set; }
        public Nullable<double> acousticness { get; set; }
        public Nullable<double> instrumentalness { get; set; }
        public Nullable<int> mode { get; set; }
        public Nullable<int> time_signature { get; set; }
        public Nullable<double> duration { get; set; }
        public Nullable<double> loudness { get; set; }
        public string audio_md5 { get; set; }
        public Nullable<double> valence { get; set; }
        public Nullable<double> danceability { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ICollection<UserTrack> UserTracks { get; set; }
    }
}
